name: Deploy to Azure App Service

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'README.md'

env:
  AZURE_WEBAPP_NAME: bookify
  NODE_VERSION: '20.x'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: ðŸ—‘ï¸ Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: 'development'
          onlyRemoveDeployments: true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm' 

      - name: Create .env file for server
        run: |
          echo "SQLITE_DB=${{ secrets.SQLITE_DB }}" >> ./server/.env
          echo "TYPEORM_CLI=${{ secrets.TYPEORM_CLI }}" >> ./server/.env
          echo "APP_PORT=${{ secrets.APP_PORT }}" >> ./server/.env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> ./server/.env
          echo "OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }}" >> ./server/.env
          echo "OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }}" >> ./server/.env
          echo "OAUTH_REDIRECT_URL=${{ secrets.OAUTH_REDIRECT_URL }}" >> ./server/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ./server/.env

      - name: Create .env file for client
        run: |
          echo "REACT_APP_APP_TITLE=${{ secrets.REACT_APP_APP_TITLE }}" >> ./client/.env
          echo "REACT_APP_APP_SLOGAN=${{ secrets.REACT_APP_APP_SLOGAN }}" >> ./client/.env
          echo "REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }}" >> ./client/.env
          echo "REACT_APP_REDIRECT_URI=${{ secrets.REACT_APP_REDIRECT_URI }}" >> ./client/.env
          echo "REACT_APP_BACKEND_ENDPOINT=${{ secrets.REACT_APP_BACKEND_ENDPOINT }}" >> ./client/.env
          echo "REACT_APP_ENVIRONMENT=${{ secrets.REACT_APP_ENVIRONMENT }}" >> ./client/.env
          echo "BUILD_PATH=${{ secrets.BUILD_PATH }}" >> ./client/.env

      - name: Install dependencies using npm workspaces
        run: npm install

      - name: Build shared dependencies
        run: npm run build:shared

      - name: Run database migrations
        run: npm run migration:run

      - name: Build all dependencies
        run: npm run build

      - name: Archive build files
        run: zip -r deployment.zip . -x "node_modules/*" -x "client/node_modules/*" -x "server/node_modules/*" -x "shared/node_modules/*"
  
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: bookify-app
          path: deployment.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: bookify-app
          path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - cleanup
    environment:
      name: 'development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: bookify-app

      - name: Unzip build files
        run: unzip deployment.zip

      - name: Remove archived file
        run: rm deployment.zip

      - name: Deploy to Digital Ocean
        uses: digitalocean/app_action/deploy@v2     
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
          app_name: ${{ secrets.DIGITAL_OCEAN_APP_NAME }}